Smarter patches-missing 2005-11-04  Andy Wingo  <wingo@pobox.com>
	* scripts/patches-missing: Use {arch}/+upstream if available.
	Don't print diffs any more, just show the patches that are
	missing. Let --full do a cat-archive-log on the patch.

diff --git a/scripts/patches-missing b/scripts/patches-missing
--- a/scripts/patches-missing
+++ b/scripts/patches-missing
@@ -6,42 +6,63 @@ if test -z "$TLA"; then
   TLA=`which tla || which baz`
 fi
 
+if ! $TLA tree-id 2>&1 >/dev/null; then
+  echo "Error: not in a valid arch working tree." >&2
+  exit 1
+fi
+
 usage() {
-  echo "usage: $0 [--full] ARCHIVE-NAME" >&2
+  echo "usage: $0 [--full] [FQVN]" >&2
   echo >&2
-  echo "Prints the patches from the current tree missing in ARCHIVE-NAME." >&2
+  echo "Prints the patches from the current tree missing in FQVN," >&2
+  echo "defaulting to {arch}/+upstream." >&2
   exit 1
 }
 
-if test $# -eq 0; then
-  usage
-fi
-
-if test $1 = "--full"; then
+if test $# -ge 1 -a "$1" = "--full"; then
   full=true
   shift
 else
   full=false
 fi
 
-test $# -eq 1 || usage
+if test $# -eq 0; then
+  if test -f `$TLA tree-root`/{arch}/+upstream; then
+    upstream=`cat $($TLA tree-root)/{arch}/+upstream`
+  else
+    echo "Error: No upstream version specified and {arch}/+upstream not found." >&2
+    exit 1
+  fi
+else
+  test $# -eq 1 || usage
+  upstream=$1
+fi
 
-archive=$1
-version=`$TLA parse-package-name $($TLA tree-version)`
 dir=`mktemp -d`
 cwd=`pwd`
 logs1=`mktemp`
 logs2=`mktemp`
+out=`mktemp`
 
-$TLA get -s $archive/$version $dir/working-copy
+$TLA get -s $upstream $dir/working-copy
 $TLA logs -f --merges -d $dir/working-copy | grep -v 'merges in' | tr -d ' ' > $logs1
 $TLA logs -f --merges -d . | grep -v 'merges in' | tr -d ' ' > $logs2
 
+# no idea why i have to use tee here
+diff -u0 $logs1 $logs2 | tee $out >/dev/null
+
+patches=$(cat $out \
+    | egrep -v '^(@|\+\+\+ |---)' \
+    | grep -v 'base-0' \
+    | sed -e 's/^\+//')
+
 if `$full`; then
-  diff -u10000 $logs1 $logs2 | egrep -v '^(@|\+\+\+ |---)' | grep -v 'base-0'
+  for i in $patches; do
+    $TLA cat-archive-log $i
+  done
 else
-  diff -u0 $logs1 $logs2 | egrep -v '^(@|\+\+\+ |---)' | grep -v 'base-0'
+  echo $patches
 fi
 
-rm -f $logs1 $logs2
+rm -f $logs1 $logs2 $out
 rm -rf $dir
